spring:
  application:
    name: winecellarsql
  datasource:
    url: jdbc:mysql://localhost:3306/cellar
    username: root
    password: root 
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8081
  error:
    include-stacktrace: always
    include-exception: true
